name: CI

on:
  push:
    branches:
      - main
      - devops/cloud-platform
    pull_request:
      branches:
       - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout repository
       uses: actions/checkout@v4 

     - name: Set up python
       uses: actions/setup-python@v5
       with:
        python-version: "3.11"

     - name: Install dependencies
       run: pip install -r requirements.txt  

     - name: Check python syntax
       run: python -m compileall -q app.py main.py modules pipelines

     - name: Build Docker Image
       run: docker build -t doc-to-markdown .        